### ISSUE TITLE
Automated development cluster setup and Carbyne Stack deployment

### ISSUE THREAD

**Issue by sbckr** [carbynestack/carbynestack#14]
For testing and development purposes, it is important to have a local Carbyne Stack cluster available. The documentation on the [website](https://carbynestack.io/getting-started/) provides a step-by-step instruction for setting up and preparing two Kind clusters, and deploying the Carbyne Stack services. However, performing these steps manually can be error-prone or tedious if they have to be done on a regular basis.

To improve usability and thus provide a more convenient experience when setting up Carbyne Stack, it would be great to have scripts available that perform all necessary steps to make a Carbyne Stack cluster available and maybe even verify correctness / integrity.

These scripts could include the following functions:
(where `[M]` describes mandatory and `[O]` optional functions)
- [M] Create and prepare two kind clusters
  - [O] with customizable cluster names
  - [O] with customizable cluster subnets / IPs
- [O] Pre-fetch all required Docker images and inject them into the Kind clusters to avoid unnecessary traffic and reduce deployment time
- [M] Deploy Carbyne Stack Virtual Cloud Partners (deploy all required services on all of the Kind cluster
- [O] Teardown of the VCPs

A initial set of [scripts](/carbynestack/carbynestack/tree/deployment-scripts/scripts) has been uploaded to the branch [deployment-scripts](/carbynestack/carbynestack/tree/deployment-scripts) as a baseline and guidance for implementation.

**Comment by strieflin** [comment]
Has been implemented as IaC in #76.
