### ISSUE TITLE
During setup helm failes to fetch oauth token

### ISSUE THREAD

**Issue by grevend-bosch** [carbynestack/carbynestack#18]
Currently, the setup process on the Carbyne Stack website is failing with the following output:

![cs-setup-issue](https://user-images.githubusercontent.com/88314907/143023902-6da9074a-5285-458a-b3a4-bb1d1dd114df.png)

It appears like Carbyne Stack docker images cannot be resolved using the helmfile because of an authorization failure triggered by a missing OAuth token. Since all images should be accessible without authentication, this seems to be the result of a bug.

**Comment by sbckr** [comment]
@grevend-bosch Could you please verify if this issue still exists as the deployment (currently) appears to be successful?

**Comment by grevend-bosch** [comment]
> @grevend-bosch Could you please verify if this issue still exists as the deployment (currently) appears to be successful?

@sbckr I can confirm that the problem still occurs, both for the original setup state and after a clean install.

**Comment by grevend-bosch** [comment]
Update: A complete reinstallation of the operating system and the necessary dependencies seems to have solved the problem.
