### ISSUE TITLE
Orgranizational README

### ISSUE THREAD

**Issue by jaredweinfurtner** [carbynestack/carbynestack#28]
GitHub has a special `.github` repository where we can place an organizational `README.md` that is displayed when someone lands on our GitHub organization:  https://github.com/carbynestack

It should be placed in: `https://github.com/carbynestack/.github/profile/README.md` and GitHub automagically picks it up.

See [twitter ](https://github.com/twitter) as an example:
![image](https://user-images.githubusercontent.com/25351659/147229583-63b215d7-cc32-4a81-af84-dbb40d69f8a8.png)

**Comment by strieflin** [comment]
That's cool. I'll work on this issue.

**Comment by strieflin** [comment]
Organization profile is deployed. @jaredweinfurtner: Please review directly at https://github.com/carbynestack. 

`CODE_OF_CONDUCT.md` and `CONTRIBUTING.md` files have to be removed from all CS repositories before this can be closed:

- [ ] carbynestack.github.io
- [ ] amphora
- [ ] cli
- [ ] java-http-client
- [ ] castor
- [ ] klyshko
- [ ] cli-ng
- [ ] ephemeral
- [ ] mp-spdz-integration
- [ ] common
- [ ] carbynestack
- [ ] base-images

**Comment by strieflin** [comment]
The open tasks described in https://github.com/carbynestack/carbynestack/issues/28#issuecomment-1008812515 will not be addresses as the mentioned files anyway contain links to the respective file in carbynestack/carbynestack.
