### ISSUE TITLE
Fork-originated Pull Requests not running github actions workflows

### ISSUE THREAD

**Issue by strieflin** [carbynestack/carbynestack#30]
The current setup for probably all our repositories does not run workflows on pull requests from forks. The root cause is that the workflow runs on `push` instead of `pull_request` events. See e.g. https://github.com/nasa/cFS/issues/169 for more information.

**Comment by strieflin** [comment]
Has been resolved with  carbynestack/amphora#18 and  carbynestack/amphora#20. Needs to be done for the other repositories as well.

**Comment by grevend** [comment]
@strieflin @sbckr https://github.com/carbynestack/common/pull/39 & https://github.com/carbynestack/cli-ng/pull/93 should resolve this issue for common & cli-ng.

**Comment by strieflin** [comment]
Seemingly not yet implemented for all repositories with a build process:

- [ ] carbynestack.github.io
- [ ] java-http-client
