### ISSUE TITLE
Provide Pregenerated Tuple files for new MP-SPDZ Version

### ISSUE THREAD

**Issue by kindlich** [carbynestack/carbynestack#36]
After carbynestack/base-images#5 the Images are now built with another MP-SPDZ Version.
In that version the format of the tuple files was changed (they now include a ~32bit file header).

There is an open PR carbynestack/cli/pull/19 to adapt the CLI to work with the new Tuple files.
If that PR goes through and we update the Stack-Documentation to use the new cs.jar, then we also need pre-generated tuple files for that version.

**Comment by strieflin** [comment]
The archive with pregenerated tuples previously has been part of the carbynestack/base-images repository but has been removed recently. I'd propose to provide the new one here in carbynestack/carbynestack. The tuples must be generated using `Fake-Offline.x` from [MP-SPDZ](https://github.com/data61/MP-SPDZ/releases) v0.2.8. Primes and mac key shares are to be taken from [here](https://github.com/carbynestack/carbynestack/blob/756a5c5882aa95292b21acabfcbb13230372db41/helmfile.d/0200.amphora.yaml). File names may have changed, so the tutorial on the website generated from carbynestack/carbynestack.github.io might need an update. See the [old tuple archive](https://github.com/carbynestack/base-images/raw/3595c5427915b2f9e1f22804e3f742cda9e72312/fake-crypto-material.zip) for reference.

**Comment by kindlich** [comment]
I don't think anything changed in the tuple format since v0.2.8, but should we just in case use the same version as the new base-image MP-SPDZ (Git-Hash `642d11f`)?

Also, who will create that archive?
Is that something we can do, or something you will do to make sure it matches some compliance standards?

**Comment by strieflin** [comment]
> I don't think anything changed in the tuple format since v0.2.8, but should we just in case use the same version as the new base-image MP-SPDZ (Git-Hash `642d11f`)?

Yes, that's probably the safest approach. One could just copy the tuples from the docker image.

> Also, who will create that archive? Is that something we can do, or something you will do to make sure it matches some compliance standards?

No compliance here as the archive only contains the tuples. Happy to review a PR on this 😁.
