### ISSUE TITLE
Update kubernetes to a supported version

### ISSUE THREAD

**Issue by grafjo** [carbynestack/carbynestack#39]
In the `Plattform Setup` guide, the used k8s version is v1.18.19 (see `kind create cluster --name apollo --image kindest/node:v1.18.19`) and this version is a little bit outdated and [EOL was on 18 Jun 2021](https://endoflife.date/kubernetes).

Bumping k8s version to a supported one, we need to keep in mind that we also have to update a lot of dependencies like istio / knative / postgres operator etc.

**Comment by strieflin** [comment]
Resolving this requires the following updates to be made:

- [ ] Update the tutorials in the website
- [ ] Update the Ephemeral Network CRD as CRDs seem to be checked more rigorously in newer versions in K8s which leads to the ports not being set.
- [ ] Perform an E2E test

**Comment by sbckr** [comment]
@strieflin PR have been reviewed.

E2E test successful (Millionaires Problem) as described by the updated instructions

**Comment by strieflin** [comment]
Thank you @sbckr and @varasu for helping with this. All PRs have been merged. Closing this.
