### ISSUE TITLE
Enable GH Discussions for Carbynestack

### ISSUE THREAD

**Issue by sbckr** [carbynestack/carbynestack#4]
Open communication with the community and interested people is one of the most important aspects for a successful open source project. 
A space for public discussion, a section for Q&A or the sharing of a vision can therefore also be a great contribution to the development of a community and its maintenance for Carbyne Stack.

[GitHub Discussion ](https://docs.github.com/en/discussions/quickstart) could provide a relevant contribution to achieve this.

@strieflin @grevend-bosch Please share your thoughts

**Comment by grevend-bosch** [comment]
Open communication is definitely the most crucial part of working well with the community. GitHub Discussions seems to a offer a very convenient platform for this kind of need for an open and collaborative forum. Furthermore staying within the GitHub ecosystem gives us access to features such as [discussion based issue creation](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue#creating-an-issue-from-discussion).

Regarding the Q&A, I would probably prefer to track the most common questions in the GitHub Wiki or on our website.

**Comment by strieflin** [comment]
Agree with @grevend-bosch that Q&A and things not directly related to CS development should land on the website. What I am not sure about is whether discussions in issues (like the discussion here) + website isn't already enough for the time being.

**Comment by grevend-bosch** [comment]
> Agree with @grevend-bosch that Q&A and things not directly related to CS development should land on the website. What I am not sure about is whether discussions in issues (like the discussion here) + website isn't already enough for the time being.

@strieflin As long as the discussion is related to an issue, it is definitely better to leave it there. If, however, there is no underlying issue, but the community simply wants to exchange ideas, a separate discussion forum makes more sense.

**Comment by strieflin** [comment]
> @strieflin As long as the discussion is related to an issue, it is definitely better to leave it there. If, however, there is no underlying issue, but the community simply wants to exchange ideas, a separate discussion forum makes more sense.

Even in that case an issue can be created and labelled accordingly, e.g. with an "enhancement" (= "New feature or request) label. We should avoid confusing contributors / users with a multitude of communication channels. Maybe we should have a look at other OS projects to see what people are used to and meet their expectations / fit their habits.

**Comment by sbckr** [comment]
> > @strieflin As long as the discussion is related to an issue, it is definitely better to leave it there. If, however, there is no underlying issue, but the community simply wants to exchange ideas, a separate discussion forum makes more sense.
> 
> Even in that case an issue can be created and labelled accordingly, e.g. with an "enhancement" (= "New feature or request) label. We should avoid confusing contributors / users with a multitude of communication channels. Maybe we should have a look at other OS projects to see what people are used to and meet their expectations / fit their habits.

I'd agree with @grevend-bosch. Although we're having a discussion here and a _question_ label exists, having a general discussion as an issue seems wrong to me.
However, there are other options such as a Discord channel. Maybe we should wait and see what others would like to have available.

**Comment by grevend-bosch** [comment]
> > @strieflin As long as the discussion is related to an issue, it is definitely better to leave it there. If, however, there is no underlying issue, but the community simply wants to exchange ideas, a separate discussion forum makes more sense.
> 
> Even in that case an issue can be created and labelled accordingly, e.g. with an "enhancement" (= "New feature or request) label. We should avoid confusing contributors / users with a multitude of communication channels. Maybe we should have a look at other OS projects to see what people are used to and meet their expectations / fit their habits.

As long as it is a question or a feature suggestion, yes. But when it comes to exchanging ideas or gaining feedback for your own projects based on Carbyne Stack, we probably don't want these as issues. Such contributions are nevertheless important to foster a community and sooner or later we will need a forum for such an exchange anyway.

**Comment by strieflin** [comment]
We should think about concrete discussion topics that are not a feature request / proposal (= issue) and not technical documentation (= website). If we can come up with (m)any there would be a need for the discussion forum **now** from my point of view, if not than not. We could also wait whether people start to "abuse" the issue tracker for things that are rather general discussions.

**Comment by grevend-bosch** [comment]
> > > @strieflin As long as the discussion is related to an issue, it is definitely better to leave it there. If, however, there is no underlying issue, but the community simply wants to exchange ideas, a separate discussion forum makes more sense.
> > 
> > 
> > Even in that case an issue can be created and labelled accordingly, e.g. with an "enhancement" (= "New feature or request) label. We should avoid confusing contributors / users with a multitude of communication channels. Maybe we should have a look at other OS projects to see what people are used to and meet their expectations / fit their habits.
> 
> I'd agree with @grevend-bosch. Although we're having a discussion here and a _question_ label exists, having a general discussion as an issue seems wrong to me.
> However, there are other options such as a Discord channel. Maybe we should wait and see what others would like to have available.

In itself, I think the idea of ​​waiting for feedback from the community is pretty good. Especially to be present on the platforms that are actually used by those interested in our project. Nevertheless, we should not forget that if we choose a platform outside of GitHub, we also lose the direct integration (see my first comment).

**Comment by strieflin** [comment]
We now have our [discord server](https://discord.gg/5QK6eSZZhk) for all kinds of discussions on CS.
