### ISSUE TITLE
Implement triaging process

### ISSUE THREAD

**Issue by strieflin** [carbynestack/carbynestack#42]
I think it is time to professionalize our issue / PR ingest process by implementing a _triage_ process. As of the Kubernetes maintainers (see [here](https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md))

> Issue triage is a process by which a SIG intakes and reviews new GitHub issues and requests, and organizes them to be actioned - either by its own members, or by other SIGs. Triaging involves categorizing issues and pull requests based on factors such as priority/urgency, SIG ownership of the issue, and the issue kind (bug, feature, etc.).

According to them _triaging_ has the following benefits, such as

>  - Speeding up issue management
>  - Keeping contributors engaged by shortening response times
>  - Preventing work from lingering endlessly
>  - Replacing special requests and one-offs with a neutral process that acts like a boundary
>  - Greater transparency, interesting discussions, and more collaborative, informed decision-making
>  - Building prioritization, negotiation and decision-making skills, which are critical to most tech roles
>  - Reinforcement of SIG community and culture

I think there is room for improvement in several of these areas in the Carbyne Stack project, hence my request to implement a triage process.

Personally, I am inclined to go for the Linux Foundation, in particular the CNCF, when we decide it is time to donate the project to a foundation. Hence, it makes a lot of sense for me to adopt their process (when it makes sense) already now. However, deploying the heavy machinery they use, like Prow, would be overkill as of today considering the current size of the Carbyne Stack community. 

Hence, my suggestion is to implement a lightweight version of the process described [here](https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md). This would involve the following steps:

- [x] Select the subset of labels we actually want to use. In my opinion that should be the `lifecycle/`, `triage/`, `kind/`, and `priority/` labels _classes_ and the `needs-triage` label (subset of [these](https://github.com/kubernetes/kubernetes/labels?q=lifecycle%2F+triage%2F+kind%2F+priority%2F+needs-triage)).
- [x] Come up with a process description (as part of the contributor guide) that heavily borrows from the K8s process description linked above.
- [x] Define the selected labels (plus maybe others) as the default set of labels in the CS org.
- [x] Adjust the labels in the existing repositories to include the selected labels. It has to be discussed whether the existing ones should be renamed or kept. Removal is no good idea and may be even not possible as existing issues and PRs make use of them. It might make sense to write a script to do this daunting job.
- [x] Configure the stale plugin to act in accordance with the process description (see #22).

Thoughts @sbckr, @jaredweinfurtner?

**Comment by strieflin** [comment]
One can search for all issues in a specific org with any of the given labels (ORed) by using `user:carbynestack is:issue label:"<label-1>", label:"<label-2>"` in the Github search bar. See [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) for what is possible. 

Guess this will become very handy in the triaging session to quickly find all relevant issues. Same works for PRs.

**Comment by strieflin** [comment]
The `needs-triage` label has to be assigned to all newly opened and reopened issues and PRs. This can be achieved easily with GHA as described [here](https://docs.github.com/en/actions/managing-issues-and-pull-requests/adding-labels-to-issues).

**Comment by strieflin** [comment]
I provided a first proposal for the triaging process as a guide here #44.

**Comment by strieflin** [comment]
My proposal would be to use [these labels](https://github.com/kubernetes/kubernetes/labels?q=lifecycle%2F++triage%2F+kind%2F+priority%2F+needs-triage+) with their respective meaning except the following:

- `do-not-merge/needs-kind`
- `kind/api-change`
- `kind/deprecation`
- `kind/design`
- `lifecycle/active`
- `needs-kind`
- `needs-priority`
- `sig/cluster-lifecycle`

**Comment by strieflin** [comment]
Labels in existing repositories have been updated using a small tool written in golang (see carbynestack/.github#3).

**Comment by strieflin** [comment]
Need your help now @jaredweinfurtner to implement the assignment of the `needs-triage` label (see https://github.com/carbynestack/carbynestack/issues/42#issuecomment-1259572577) and configuring the stale plugin (see https://github.com/carbynestack/carbynestack/issues/42#issue-1364844328).

**Comment by jaredweinfurtner** [comment]
@strieflin The re-usable workflows (for both auto-labeling of triage and stale-action cleanup) are in this PR: https://github.com/carbynestack/.github/pull/2.  


Once that is merged, please review the PRs for each repository to utilize these reusable workflows:

* cli - https://github.com/carbynestack/cli/pull/27
* cli-ng - https://github.com/carbynestack/cli-ng/pull/97
* carbynestack.github.io - https://github.com/carbynestack/carbynestack.github.io/pull/70
* castor - https://github.com/carbynestack/castor/pull/40
* java-http-client - https://github.com/carbynestack/java-http-client/pull/16
* amphora - https://github.com/carbynestack/amphora/pull/38
* carbynestack - https://github.com/carbynestack/carbynestack/pull/43
* common - https://github.com/carbynestack/common/pull/41
* ephemeral - https://github.com/carbynestack/ephemeral/pull/29
* mp-spdz-integration - https://github.com/carbynestack/mp-spdz-integration/pull/17
* klyshko - https://github.com/carbynestack/klyshko/pull/7
* corporate-information - https://github.com/carbynestack/corporate-information/pull/3

**Comment by strieflin** [comment]
`base-images` and `cli-ng` still not done.

**Comment by strieflin** [comment]
Changes in `cli-ng` done (carbynestack/cli-ng#97).

**Comment by strieflin** [comment]
Changes in `base-images` done (carbynestack/base-images#11).
