### ISSUE TITLE
Private image classification example code

### ISSUE THREAD

**Issue by LGro** [carbynestack/carbynestack#46]
I recently watched your [intro video](https://carbynestack.io/getting-started/#tldr) which contains an example application for MNIST image classification. Is the code for this example available somewhere? I'd be curious to have a look at it :relaxed:

**Comment by strieflin** [comment]
Hi @LGro,

thank you for reqching out. The MNIST demo has been developed Bosch internally. Currently, there are no plans of making it Open Source as we have other priorities ATM. In addition, MP-SPDZ has been extended with ML capabilities meanwhile with probably much better performance than our 2 year old MNIST demo. However, MP-SPDZ ML workloads are not supported yet in Carbyne Stack as we do not support the special tuple types needed as of today.

For question / support, please feel free to use our [Discord server](https://discord.gg/8sxNPCSBDk) in the future.

Closing this. Please reopen in case there are open questions.
