### ISSUE TITLE
Security assumptions

### ISSUE THREAD

**Issue by mkskeller** [carbynestack/carbynestack#5]
Is there any documentation over the security assumptions of the involved instances? More concretely, the example code involves the clients from MP-SPDZ perspective (Amphora if I understand it right) to learn and provide MAC shares. Does that mean Amphora services are understood to be part of the computation parties, or am I missing something?

**Comment by strieflin** [comment]
Hi @mkskeller,

thank you for asking the first official question! 😃 

Unfortunately, documentation around Carbyne Stack is a little scarce so far. We understand that documentation is something that is important for potential CS users and contributors and therefore added this to our roadmap (see #6).

Regarding your questions:

CS implements MPC in the client/server model as described in [1]. This means we can have a set of CS instances acting as the MPC parties (only 2 parties supported as of now) and any number of clients invoking the services provided collectively by the CS instances. In CS lingo, we refer to MPC parties as _Virtual Cloud Providers_ (VCPs) that jointly provide MPC services in a _Virtual Cloud_ (VC). Each VCP hosts an instance of the Castor, Amphora, and Ephemeral services:

- [Castor ](https://github.com/carbynestack/castor) stores offline tuples and serves them on request to Amphora and Ephemeral. 
- [Amphora](https://github.com/carbynestack/amphora) is the secret store that is used by clients to store and retrieve secrets. Amphora uses tuples from Castor to perform the secure up-/download protocols of [1] when clients up- or download secrets. 
- [Ephemeral](https://github.com/carbynestack/ephemeral) is used to execute MPC programs using MP-SPDZ. Any number of secrets can be fetched from Amphora at the beginning of an MPC program execution and any number of secrets can be written to Amphora at the end. Ephemeral fetches tuples from Castor consumed throughout the execution of the MPC program. This is not implemented so far. Hence, the disclaimer that we use the MPC protocols in an insecure way. However, this has high priority on our roadmap.

These VCP services interact locally, with their counterparts in other VCPs, and with CS clients. There are three communication interfaces involved:

1. The _Intra-VCP interface_ is used to communicate internally within a single VCP. For example, Ephemeral talks to the co-located Castor service to fetch offline tuples.
2. The _Inter-VCP interface_ is used to coordinate operations between VCPs. An example for this is the interaction required between Amphora instances to perform the secure up-/download protocols of [1].
3. The _client interface_ is used by clients to invoke the CS services of the VC, e.g. uploading a secret to Amphora or triggering an MPC program execution via Ephemeral.

A design goal of CS is that each of the VCP services can be scaled independently and automatically. 

Hope that helps clarifying things.

[1] Ivan Damgård, Kasper Damgård, Kurt Nielsen, Peter Sebastian Nordholt, Tomas Toft: Confidential Benchmarking based on Multiparty Computation. IACR Cryptology ePrint Archive 2015: 1006 (2015) https://eprint.iacr.org/2015/1006

**Comment by mkskeller** [comment]
Thank you, this answers my question.

**Comment by strieflin** [comment]
Great! Let us know in case you have any further questions.
