### ISSUE TITLE
Tuples are not available after restarting the services

### ISSUE THREAD

**Issue by sbckr** [carbynestack/carbynestack#59]
# Summary 

When a cluster, or especially MinIO is restarted, all previously Tuples are no longer accessible and Castor will keep raising exceptions when Tuples are been requested from any service or client.

# Details

After a CS Cluster has been restarted, Castor is still able to retrieve stored TupleChunk metadata from the PostgreSQL database and therefore tries to read and return the related bytes (tuple data) from Minio. However all previously stored objects in Minio are no longer available, as MinIO is not using a persisted volume to store data.

> ## Persisting your database
>
> If you remove the container all your data will be lost, and the next time you run the image the database will be reinitialized. To avoid > this loss of data, you should mount a volume that will persist even after the container is removed.
>
> For persistence you should mount a directory at the /data path.
>
>```
> $ docker run --name minio \
>    --publish 9000:9000 \
>    --publish 9001:9001 \
>    --volume /path/to/minio-persistence:/data \
>    bitnami/minio:latest
> ```
> Source [Persisting your database](https://hub.docker.com/r/bitnami/minio/)

**Comment by strieflin** [comment]
Has been addressed in #87.
