### ISSUE TITLE
Add support for edaBits

### ISSUE THREAD

**Issue by strieflin** [carbynestack/carbynestack#70]
_Extended doubly-authenticated bits_ (edaBits) [EGK+20] are CR tuples composed of a secret shared integer in the arithmetic domain combined with its bit decomposition shared in the binary domain. They are used for MPC circuits that need to switch between arithmetic and binary representation.

Implementing edaBit support requires

- [ ] Providing support for storing and retrieving the new tuple type in Castor
- [ ] Fetching and feeding the new tuple type in Ephemeral
- [ ] Adding the new tuple type to the Klyshko Integration Interface (KII) and to the existing CRG implementations

[EGK+20] Daniel Escudero, Satrajit Ghosh, Marcel Keller, Rahul Rachuri, and Peter Scholl. Improved primitives for MPC over mixed arithmetic-binary circuits. In Daniele Micciancio and Thomas Ristenpart, editors, CRYPTO 2020, Part II, volume 12171 of LNCS, pages 823–852. Springer, Heidelberg, August 2020 ([PDF](https://eprint.iacr.org/2020/338.pdf))

**Comment by sbckr** [comment]
Ressurect issue as it was closed unintentionally
