### ISSUE TITLE
Increase Knative Max Revision Timeout 

### ISSUE THREAD

**Issue by sbckr** [carbynestack/carbynestack#73]
Ephemeral builds on [Knative ](https://knative.dev) to provide its functionality and trigger program executions. 
With this dependency, the lifetime of so-called activation requests is managed on the Knative side, among others. Therefore it is also subject to the configured timeouts (e.g. see [Knative RevisionSpec](https://knative.dev/docs/serving/reference/serving-api/#serving.knative.dev/v1.RevisionSpec)). These timeouts can be configured per deployment, but must not exceed the general Knative max-revision-timeout (default is 600s). (the deployment will fail if not set properly). 
However, since ephemeral program executions can generally take longer, the maximally permissible timeout should be configured accordingly high when deploying Knative.
For this the configuration should be adapted possibly as follows:
```bash
cat <<EOF | envsubst > knative-serving.yaml
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  version: 1.8.2
  manifests:
    - URL: https://github.com/carbynestack/serving/releases/download/v1.8.2-multiport-patch/serving-crds.yaml
    - URL: https://github.com/carbynestack/serving/releases/download/v1.8.2-multiport-patch/serving-core.yaml
    - URL: https://github.com/knative/net-istio/releases/download/v1.8.2/release.yaml
    - URL: https://github.com/knative/net-certmanager/releases/download/v1.8.2/release.yaml
  config:
     domain:
        ${EXTERNAL_IP}.sslip.io: ""
     defaults:
        max-revision-timeout-seconds: "36000"
EOF
kubectl apply -f knative-serving.yaml
```

**Comment by strieflin** [comment]
Addressed in #78.
