### ISSUE TITLE
Improve publish-and-release workflow

### ISSUE THREAD

**Issue by sbckr** [carbynestack/carbynestack#8]
The `publis-and-release` (e.g. see [amphora](https://github.com/carbynestack/amphora/blob/bde5fd9a8b78274dcbb519d05da6ecd5dfa9705d/.github/workflows/publish-and-release.yaml)) workflow includes three basic tasks:

1. creation of a release draft with the disclosure documentation
2. creation and upload of the artifacts
3. publishing the release

If the workflow fails at step number 2 or later, it will result in an unclean release status. This includes for example:
- A commit was tagged without a release being completed
- A release draft was created, but never published
- Individual artifacts were created and uploaded

However, the workflow should be adjusted so that, in the event of an error
- dangling artifacts are removed
- the git tag is removed
- the release draft is deleted

**Comment by strieflin** [comment]
Seems to happen very infrequently. Hence, can be tackled manually for the time being.
