### ISSUE TITLE
Deployment broken with latest Helm Charts

### ISSUE THREAD

**Issue by sbckr** [carbynestack/carbynestack#9]
With the latest breaking changes to Helm Release [3.7.0](https://github.com/helm/helm/releases/tag/v3.7.0), newly packaged charts are no longer compatible with prior versions:

>In addition, a change to the experimental OCI manifest format was introduced, preventing Helm 3.7 from fetching charts built with older versions of the experimental OCI feature. Users will need to re-package and upload their OCI charts when upgrading to Helm 3.7

GitHub is already shipping Helm 3.7.0 with their latest [Ubuntu 20.04 virtual-environment](https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210919.1). This has made it necessary to upgrade the `helm-oci-chart-releaser` action in the `publish-and-release` workflow for [Amphora](https://github.com/carbynestack/amphora/pull/4), [Castor](https://github.com/carbynestack/castor/pull/4) and [Ephemeral](https://github.com/carbynestack/ephemeral/pull/5) to version [v0.3.0](https://github.com/appany/helm-oci-chart-releaser/releases/tag/v0.3.0).

However, [helmfile](https://github.com/roboll/helmfile), which is used for the deployment of a VCP's services, was not yet updated to reflect the outlined changes to Helm 3.7.0 and is therefore incompatible.

**As long as helmfile does not provide an update**, e.g. as requested by [helmfile PR#1970](https://github.com/roboll/helmfile/pull/1970),**[carbynestack](https://github.com/carbynestack/carbynestack) cannot be updated to use latest Carbyne Stack service releases**.

**Comment by sbckr** [comment]
@strieflin 
The broken build and release workflow has been addressed and resolved in the individual repositories ([amphora](https://github.com/carbynestack/amphora/pull/4), [castor](https://github.com/carbynestack/castor/pull/4) and [ephemeral](https://github.com/carbynestack/ephemeral/pull/5)). 
Next step would be to adapt the Carbyne Stack deployment (instructions) accordingly, like use latest helm, helmfile and Carbyne Stack service versions)

**Comment by strieflin** [comment]
Will take care of this.

**Comment by strieflin** [comment]
Tutorials are already using recent versions of helm (v3.7.1) and helmfile (v0.142.0). Will update only Carbyne Stack service (#25) and CLI versions (see carbynestack/carbynestack.github.io#27).
