### ISSUE TITLE
IaC configuation of CarbyneStack Microservice version numbers

### ISSUE THREAD

**Issue by jaredweinfurtner** [carbynestack/carbynestack#92]
Currently, CarbyneStack microservices' versions are hardcoded:

```javascript

const castor = new helm.release.Release(this, `castor${config.idPostfix}`, {
      provider: config.helmProvider,
      version: "0.2.0",   
      ...
```

We need to hook into the release process of each microservice to ensure deployments are up to date.

**Comment by strieflin** [comment]
What is the status of this @jaredweinfurtner?
